# Generated by Django 4.2.5 on 2023-09-30 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_lessonviewinfo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonviewinfo',
            name='last_view_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 0, 21, 54, 924410)),
        ),
        migrations.AlterField(
            model_name='lessonviewinfo',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='views', to='study.lesson'),
        ),
    ]
